# Generated by Django 2.0.5 on 2018-05-27 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('codigo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ejecucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Lenguaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=25)),
                ('segundo_nombre', models.CharField(max_length=25)),
                ('primer_apellido', models.CharField(max_length=25)),
                ('segundo_apellido', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('pass1', models.CharField(max_length=25)),
                ('edad', models.IntegerField()),
                ('ciudad', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=40)),
                ('lenguaje', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='lenguaje',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablas.Tipo_Lenguaje'),
        ),
        migrations.AddField(
            model_name='ejecucion',
            name='lenguaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablas.Lenguaje'),
        ),
        migrations.AddField(
            model_name='ejecucion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablas.Usuario'),
        ),
        migrations.AddField(
            model_name='codigo',
            name='ejecucion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tablas.Ejecucion'),
        ),
    ]
